config/routes.rb
Rails.application.routes.draw do
  resources :things

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  

   root 'things#index'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

   	def self.from_omniauth_started(auth, current_user)
   	  user = User.find(current_user.id)
	  user.update_attributes(provider: auth.provider, uid: auth.uid)
	  user 
	end

	def self.from_omniauth(auth)
	  user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name
	  end
	  user.skip_confirmation!
	  user
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

      before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :uid, :provider) }
            #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    if user_signed_in? 
  		@user = User.from_omniauth_started(request.env["omniauth.auth"], current_user)
	else
    	@user = User.from_omniauth(request.env["omniauth.auth"])
    end

	if @user.persisted?
	  sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
	  set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
	else
	  session["devise.facebook_data"] = request.env["omniauth.auth"]
	  redirect_to new_user_registration_url
	end
	
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @things = Thing.all
    respond_with(@things)
  end

  def show
    respond_with(@thing)
  end

  def new
    @thing = Thing.new
    respond_with(@thing)
  end

  def edit
  end

  def create
    @thing = Thing.new(thing_params)
    if @thing.save
      respond_with(@thing)
      Example.welcome_email(@thing).deliver
    end
  end

  def update
    @thing.update(thing_params)
    respond_with(@thing)
  end

  def destroy
    @thing.destroy
    respond_with(@thing)
  end

  private
    def set_thing
      @thing = Thing.find(params[:id])
    end

    def thing_params
      params.require(:thing).permit(:name, :description, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/example/welcome_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Welcome to example.com, <%= @user.name %></h1>
    <p>
      You have successfully signed up to example.com,
      your username is: <%= @user.name %>.<br>
    </p>
    <p>
      To login to the site, just follow this link: <%= @url %>.
    </p>
    <p>Thanks for joining and have a great day!</p>
  </body>
</html>

app/views/example/welcome_email.text.erb
Welcome to example.com, <%= @user.name %>
===============================================
 
You have successfully signed up to example.com,
your username is: <%= @user.name %>.
 
To login to the site, just follow this link: <%= @url %>.
 
Thanks for joining and have a great day!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailSender</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<%if user_signed_in?%>
<h1><%=current_user.name%></h1> -- <h3><%=current_user.email%></h3>
<%=link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete%><br>
<%=link_to "Contraseña", edit_user_registration_path%>
<%else%>
<%=link_to "Registrarse", new_user_registration_path%> <br>
<%=link_to "Iniciar sesión", new_user_session_path%>	
<%end%>

<%= yield %>

</body>
</html>

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1>Listing things</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td><%= thing.description %></td>
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing', new_thing_path %>
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @thing.description %>
</p>

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>